import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillLinkedin,
  AiFillGithub,
  AiFillTwitterCircle,
  AiFillInstagram,
  AiFillYoutube,
} from "react-icons/ai";
import jake from "../public/jacob_daurham.png";
import piroutinePage from "../public/piroutine_page.png";
import piroutineGithub from "../public/piroutine_github.png";
import piroutineGif from "../public/piroutine_sq_gif.gif";

const InlineTxt = ({ text, darkMode }: { text: string; darkMode: boolean }) =>
  darkMode ? (
    <span className=" text-teal-300">{text}</span>
  ) : (
    <span className=" text-teal-700">{text}</span>
  );

const getYearsOfJourney = () => String(new Date().getFullYear() - 2009);

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Jacob Daurham Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-900">
        <section className=" min-h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-xl font-extrabold dark:text-moonl">Daurham</h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-moonl"
                />
              </li>
              <li>
                <a
                  className=" bg-gradient-to-r from-cyan-500 to-teal-800 text-white px-4 py-2 rounded-md ml-8"
                  href="https://docs.google.com/document/d/1BuWNK6pHv0wWnTUAfriOv46RL_x6LvSkpYA3HpRpqbs/edit?usp=sharing"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center py-10">
            <h2 className=" text-5xl py2 text-teal-600 font-medium md:text-6xl">
              Jake Daurham
            </h2>
            <h3 className=" text-2xl py2  text-slate-500 md:text-3xl overline mt-3">
              Software Engineer | Artist
            </h3>
            <p className="text-md py5 leading-8 text-slate-700 md:text-xl max-w-md mx-auto">
              Passionately studying the world around me. Motivated to{" "}
              <InlineTxt darkMode={darkMode} text="Create" /> a better one.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-5 py-3 text-slate-700 md:gap-16 dark:text-slate-400">
            <a
              href="https://instagram.com/captain_daurham"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillInstagram />
            </a>
            <a
              href="https://github.com/daurham"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>
            <a
              href="https://www.linkedin.com/in/daurham"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin />
            </a>
            <a
              href="https://twitter.com/daurham"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillTwitterCircle />
            </a>
            <a
              href="https://youtube.com/daurham"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillYoutube />
            </a>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={jake} layout="fill" objectFit="cover" alt="" />
          </div>
        </section>

        {/* Second Page */}
        <section>
          <div>
            <h3 className="text-3xl py-1 text-center mt-10 dark:text-slate-300">
              Portfolio
            </h3>
            {/* <h3 className="text-3xl py-1 dark:text-slate-300">What am I</h3> */}
            {/* <p className="text-md py5 leading-8 text-slate-700 dark:text-slate-500"></p> */}
            <p className="text-md py5 text-center leading-8 text-slate-700 dark:text-slate-500">
              I've spent the last {getYearsOfJourney()} years of my life as a
              project specialist in design, the last{" "}
              {Number(getYearsOfJourney()) - 4} taking on commissions for my
              work and the last {new Date().getFullYear() - 2020} years
              averaging 12+ hours a day into programming.
            </p>
            <p className="text-md py5 text-center leading-8 text-slate-700 dark:text-slate-500">
              <span className="text-2xl ">My work</span> shows a willingness to{" "}
              <InlineTxt text="experiment" darkMode={darkMode} /> outside my
              comfort zone, <InlineTxt text="learn" darkMode={darkMode} /> new
              technologies and <InlineTxt text="innovate" darkMode={darkMode} />{" "}
              abstract solutions.
            </p>
            {/* 
              My work shows
              determination to learn new skills, create abstract solutions and
              excel wherever I go. */}
            {/* </p>
            <p className="text-md py5 indent-5 leading-8 text-slate-700 dark:text-slate-500">
              Having spent my last 2 contracts as a student mentor in a software
              engineering bootcamp, I'm coming in with a strong set of soft
              skills, strong full-stack / javascript fundamentals, refined best
              practices, the ability to explain technical concepts in layman's
              terms and a stoic work ethic that emphasizes personal growth.
            </p>
            <p className="text-md py5 text-center leading-8 text-slate-700 dark:text-slate-200"> */}
            {/* <span className="text-xl">I am</span> a{" "} */}
            {/* <InlineTxt darkMode={darkMode} text="Software Engineer" />. */}
            {/* </p> */}
          </div>

          {/* CARDS */}

          <div className="md:flex gap-10 justify-center">
            {/* CARD 1 */}
            {/* <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-moon">
              <div className="flex justify-center">
                <Image
                  src={piroutinePage}
                  width={100}
                  height={100}
                  alt={"piroutine"}
                />
              </div>
              <h3 className="text-lg text-slate-700 font-medium pt-8 pb-2 dark:text-yellow-50">
                Software Engineer
              </h3>
              <p className="py-2 dark:text-slate-300">Creative solutions to problems</p>
              <h4 className="py-4 text-teal-400">Tech-Stack:</h4>
              <p className=" text-gray-800 py-1 dark:text-slate-400">TypeScript</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">React</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">Express.js</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">Node.js</p>
            </div> */}
            {/* CARD 2 */}
            {/* <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-moon">
              <div className="flex justify-center">
                <Image
                  src={piroutinePage}
                  width={100}
                  height={100}
                  alt={"piroutine"}
                />
              </div>
              <h3 className="text-lg text-slate-700 font-medium pt-8 pb-2 dark:text-yellow-50">
                Software Engineer
              </h3>

              <p className="py-2 dark:text-slate-300">Creative solutions to problems</p>
              <h4 className="py-4 text-teal-400">Tech-Stack:</h4>
              <p className=" text-gray-800 py-1 dark:text-slate-400">TypeScript</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">React</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">Express.js</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">Node.js</p>
            </div> */}
            {/* CARD 3 */}
            {/* <div className="text-center shadow-lg p-5 rounded-xl my-10 dark:bg-moon">
              <div className="flex justify-center">
                <Image
                  src={piroutinePage}
                  width={100}
                  height={100}
                  alt={"piroutine"}
                />
              </div>
              <h3 className="text-lg text-slate-700 font-medium pt-8 pb-2 dark:text-yellow-50">
                Software Engineer
              </h3>

              <p className="py-2 dark:text-slate-300">Creative solutions to problems</p>
              <h4 className="py-4 text-teal-400">Tech-Stack:</h4>
              <p className=" text-gray-800 py-1 dark:text-slate-400">TypeScript</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">React</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">Express.js</p>
              <p className=" text-gray-800 py-1 dark:text-slate-400">Node.js</p>
            </div>
          */}
          </div>
        </section>

        {/* SECTION 3 */}
        {/* PORTFOLIO */}
        <section>
          <div>
            {/* <h3 className="text-3xl py-1 dark:text-slate-300">Portfolio</h3>
            <p className="text-md py5 text-center leading-8 text-slate-500"> */}
            {/* My work shows a willingness to{" "}
              <InlineTxt text="experiment" darkMode={darkMode} /> outside my
              comfort zone, <InlineTxt text="learn" darkMode={darkMode} /> new
              technologies and <InlineTxt text="innovate" darkMode={darkMode} />{" "}
              abstract solutions. */}
            {/* </p> */}
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 text-center">
              {/* <a
                className=" text-center text-lg items-center"
                >
                <AiFillGithub />
              </a> */}
              <p className=" text-center text-lg text-slate-700 dark:text-slate-400">
                Check Out My Software Projects
              </p>
              <a
                className=" text-center text-2xl"
                href="https://github.com/daurham"
                target="_blank"
                rel="noopener noreferrer"
              >
                <InlineTxt text="HERE" darkMode={darkMode} />
              </a>
            </div>
            <div className="basis-1/3 flex-1 text-center md:flex">
              {/*         <a
              <AiFillInstagram /> 
              >
              </a>
                */}
              <p className=" text-center text-lg text-slate-700 dark:text-slate-400">
                Check Out My Design Projects
              </p>
              <a
                className=" text-center text-2xl"
                href="https://instagram.com/captain_daurham"
                target="_blank"
                rel="noopener noreferrer"
              >
                <InlineTxt text="HERE" darkMode={darkMode} />
              </a>
            </div>
            {/* <div className="basis-1/3 flex-1"> */}
            {/* <Image */}
            {/* <img */}
            {/* src={piroutineGif} */}
            {/* // src="https://media.giphy.com/media/sfz6S74HqraQRCemlz/giphy.gif"
                // src="https://media.giphy.com/media/sfz6S74HqraQRCemlz/giphy.mp4"
                // className=" rounded-lg object-cover w-100 h-100"
                // className=" rounded-lg object-cover"
                // width={"100"}
                // height={"100"}
                // layout="responsive"
                // alt={"project"} */}
            {/* /> */}
            {/* </div> */}
            {/* SDC */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                src={piroutineGithub}
                className=" rounded-lg object-cover"
                width={"100"}
                height={"100"}
                layout="responsive"
                alt={"project"}
              />
            </div> */}
            {/* FEC */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                src={piroutinePage}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt={"project"}
              />
            </div> */}
            {/* TIMER */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                src={piroutineGithub}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt={"project"}
              />
            </div> */}
            {/* Blue Ocean */}
            {/* <div className="basis-1/3 flex-1">
              <Image
                src={piroutinePage}
                className=" rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                alt={"project"}
              />
            </div> */}
          </div>
        </section>
      </main>
    </div>
  );
}
